export const requiredBody = {
  schema: {
    type: 'object',
    properties: {
      username: {
        type: 'string',
        description: 'The username of some user that is already registered.',
      },
      password: {
        type: 'string',
        description: 'The password of the mentioned user.',
      },
    },
  },
};

export const successResponse = {
  status: 200,
  schema: {
    type: 'object',
    properties: {
      accessToken: {
        type: 'string',
        description: 'The JWT token generated by the server.',
      },
    },
  },
};

export const failureResponse = {
  status: 401,
  description: 'Wrong or missing credential types',
};
